// Toate municipiile, orașele și comunele din județul Călărași.
// Lista este folosită în formularul de publicare pentru salvarea uniformă a localității.
export const LOCATII = [
  "Călărași",
  "Oltenița",
  "Budești",
  "Fundulea",
  "Lehliu-Gară",
  "Alexandru Odobescu",
  "Belciugatele",
  "Borcea",
  "Căscioarele",
  "Chirnogi",
  "Chiselet",
  "Ciocănești",
  "Curcani",
  "Cuza Vodă",
  "Dichiseni",
  "Dor Mărunt",
  "Dorobanțu",
  "Dragalina",
  "Dragoș Vodă",
  "Frăsinet",
  "Frumușani",
  "Fundeni",
  "Gălbinași",
  "Grădiștea",
  "Gurbănești",
  "Ileana",
  "Independența",
  "Jegălia",
  "Lehliu",
  "Luica",
  "Lupșanu",
  "Mânăstirea",
  "Mitreni",
  "Modelu",
  "Nana",
  "Nicolae Bălcescu",
  "Perișoru",
  "Plătărești",
  "Radovanu",
  "Roseți",
  "Sărulești",
  "Sohatu",
  "Spanțov",
  "Șoldanu",
  "Ștefan cel Mare",
  "Ștefan Vodă",
  "Tămădău Mare",
  "Ulmeni",
  "Ulmu",
  "Unirea",
  "Valea Argovei",
  "Vasilați",
  "Vâlcelele",
];
