// Lista centrală cu municipiile, orașele, comunele și satele componente
// din județul Călărași. Este folosită în toate dropdown-urile de localitate.
export const LOCATII = [
  "Alexandru Ioan Cuza",
  "Alexandru Odobescu",
  "Aprozi",
  "Arțari",
  "Belciugatele",
  "Bogata",
  "Bogdana",
  "Borcea",
  "Boșneagu",
  "Buciumeni",
  "Budești",
  "Buzoeni",
  "Ceacu",
  "Cetatea Veche",
  "Chirnogi",
  "Chiselet",
  "Ciocănești",
  "Clătești",
  "Coconi",
  "Codreni",
  "Cojești",
  "Constantin Brâncoveanu",
  "Coslogeni",
  "Coțofanca",
  "Crivăț",
  "Cucuieți",
  "Cunești",
  "Curcani",
  "Curătești",
  "Cuza Vodă",
  "Călărași",
  "Călărașii Vechi",
  "Călăreți",
  "Cândeasca",
  "Căscioarele",
  "Dichiseni",
  "Dor Mărunt",
  "Dorobanțu",
  "Dragalina",
  "Dragoș Vodă",
  "Drajna Nouă",
  "Dâlga",
  "Dâlga-Gară",
  "Dănești",
  "Dârvari",
  "Florica",
  "Floroaica",
  "Frumușani",
  "Frăsinet",
  "Frăsinetu de Jos",
  "Fundeni",
  "Fundulea",
  "Fântâna Doamnei",
  "Făurei",
  "Gostilele",
  "Gruiu",
  "Grădiștea",
  "Gurbănești",
  "Gălățui",
  "Gălbinași",
  "Gâldău",
  "Ileana",
  "Independența",
  "Iezeru",
  "Jegălia",
  "Lehliu",
  "Lehliu-Gară",
  "Libertatea",
  "Luica",
  "Lunca",
  "Lupșanu",
  "Luptători",
  "Mataraua",
  "Mihai Viteazu",
  "Mitreni",
  "Modelu",
  "Mânăstirea",
  "Măriuța",
  "Măgureni",
  "Mărculești-Gară",
  "Nana",
  "Negoești",
  "Nicolae Bălcescu",
  "Nucetu",
  "Nuci",
  "Ogoru",
  "Oltina",
  "Oltenița",
  "Orăști",
  "Ostrovu",
  "Paicu",
  "Pasărea",
  "Pelinu",
  "Perișoru",
  "Pițigaia",
  "Plumbuita",
  "Plătărești",
  "Plevna",
  "Podari",
  "Podu Pitarului",
  "Polcești",
  "Popești",
  "Postăvari",
  "Potcoava",
  "Preasna",
  "Preasna Veche",
  "Progresu",
  "Pădurișu",
  "Radu Negru",
  "Radu Vodă",
  "Radovanu",
  "Rasa",
  "Roseți",
  "Răsurile",
  "Răzvani",
  "Răzoarele",
  "Satu Nou",
  "Satnoeni",
  "Socoalele",
  "Sohatu",
  "Solacolu",
  "Spanțov",
  "Stancea",
  "Stoenești",
  "Sultana",
  "Săcele",
  "Sălcioara",
  "Săndulița",
  "Săpunari",
  "Sărulești",
  "Sărulești-Gară",
  "Sătucu",
  "Siliștea",
  "Șeinoiu",
  "Șoldanu",
  "Ștefan cel Mare",
  "Ștefan Vodă",
  "Ștefănești",
  "Tudor Vladimirescu",
  "Tăriceni",
  "Tămădău Mare",
  "Tămădău Mic",
  "Tonea",
  "Ulmeni",
  "Ulmu",
  "Unirea",
  "Valea Argovei",
  "Valea Popii",
  "Valea Presnei",
  "Valea Roșie",
  "Valea Rusului",
  "Valea Seacă",
  "Valea Stânii",
  "Vasilați",
  "Vișinii",
  "Vlad Țepeș",
  "Vlădiceasca",
  "Vlăiculești",
  "Vâlcelele",
  "Vărăști",
  "Zimbru",
  "Înfrățirea",
];
